#include <sys/types.h>
#include <sys/stat.h>
#include <signal.h>
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <stdio.h>
#include <sys/time.h>
#include <aio.h>
#include <signal.h>
#include "err_exit.h"
#include <sys/mman.h>
#include <string.h>
